var state = { summary: null, view: 'home', capabilities: [], documents: [], activity: [] };
var app = document.querySelector('#app');
var NAME_MAP = {'tt-a1i/archify':'Archify','github/spec-kit':'Spec Kit','bmad-code-org/BMAD-METHOD':'BMAD Method','langchain-ai/langchain':'LangChain','coleam00/archon':'Archon','TauricResearch/TradingAgents':'TradingAgents','nieledran/backtesting-engine':'backtesting-engine'};
var CATEGORY_MAP = {'AI_AGENT':'AI / 智能体','AI_EXPERIENCE':'AI / 体验','QUANT_DATA':'量化 / 数据','WATCHLIST':'观察清单','DEVELOPER_TOOL':'开发工具','KNOWLEDGE':'知识与方法','GENERAL':'其他'};
var STATUS_MAP = {'USED':'已实际使用','TRIAL_ENABLED':'可直接使用','ACTIVE_PATTERN':'知识库 / 方法参考','REFERENCE_ONLY':'知识库 / 方法参考','QUARANTINE_READY':'正在验证','CANDIDATE_FOR_QUARANTINE':'进入验证','BLOCKED_HUMAN':'需要你决定','FAILED_VALIDATION':'暂未采用','NOT_ADOPTED':'暂未采用','REVIEWED':'已完成判断','SCAN_SUCCESS':'扫描完成','SCAN_NOT_EVALUATED':'扫描需要注意','RUNNING':'运行中','COMPLETED':'已完成','SUCCESS':'正常','DEGRADED_HISTORY_ONLY':'有历史提醒','NOT_EVALUATED':'需要注意'};
function esc(value) { return String(value == null ? '' : value).replace(/[&<>"']/g, function (c) { return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]; }); }
function date(value, technical) { if (!value) return '暂无'; var d = new Date(value); if (isNaN(d.getTime())) return String(value); return d.toLocaleString('zh-CN', technical ? {hour12:false} : {year:'numeric',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}); }
function displayName(repo) { return NAME_MAP[repo] || String(repo || '未命名能力').split('/').pop().replace(/[-_]+/g, ' '); }
function category(value) { return CATEGORY_MAP[value] || String(value || '其他').replace(/_/g, ' '); }
function humanStatus(value) { return STATUS_MAP[value] || String(value || '暂无').replace(/_/g, ' '); }
function statusClass(value) { var s = String(value || ''); if (s === 'USED' || s === 'TRIAL_ENABLED' || s === 'SUCCESS' || s === '正常') return 'ok'; if (s.indexOf('FAIL') >= 0 || s.indexOf('NOT_ADOPTED') >= 0 || s === '异常' || s === 'NOT_EVALUATED') return 'bad'; if (s.indexOf('BLOCKED') >= 0 || s.indexOf('DEGRADED') >= 0 || s.indexOf('NEED') >= 0 || s.indexOf('提醒') >= 0) return 'warn'; if (s.indexOf('QUARANTINE') >= 0 || s.indexOf('CANDIDATE') >= 0 || s === 'RUNNING') return 'info'; return 'neutral'; }
function chip(value, label) { return '<span class="status-chip ' + statusClass(value) + '"><span class="status-dot" aria-hidden="true"></span>' + esc(label || humanStatus(value)) + '</span>'; }
function tag(label, cls) { return '<span class="tag ' + (cls || '') + '">' + esc(label) + '</span>'; }
function empty(text) { return '<div class="empty">' + esc(text) + '</div>'; }
function getJSON(url) { return fetch(url, {cache:'no-store'}).then(function (r) { if (!r.ok) throw new Error(r.statusText); return r.json(); }); }
function issueLabel(value) { return {'ACTIVE_PENDING_PACKETS':'有待处理内容','TASK_LAST_RESULT_NONZERO':'计划任务存在历史提醒','STALE_OR_MALFORMED_LOCK':'后台锁需要检查','INCOMPLETE_SCAN_RUN':'存在未完成扫描记录'}[value] || humanStatus(value); }
function cardTitle(item) { return '<div class="capability-title"><h3><a href="' + esc(item.url || '#') + '" target="_blank" rel="noreferrer">' + esc(displayName(item.repository)) + '</a></h3><div class="repo-secondary">' + esc(item.repository || '') + '</div></div>'; }
function capabilityCard(item) {
  var ask = (item.how_to_ask_codex || [])[0] || '直接描述你的目标，Codex 会判断是否相关。';
  var form = item.consumption_form === 'TOOL' ? '工具' : item.consumption_form === 'PATTERN' ? '方法参考' : '知识参考';
  return '<article class="card capability-card"><div class="card-head"><div>' + cardTitle(item) + '<div class="meta card-meta">' + esc(category(item.best_route)) + ' · ' + esc(date(item.updated_at)) + '</div></div>' + chip(item.activation_state || item.lifecycle_status, item.lifecycle_status) + '</div><p class="card-summary">' + esc(item.human_summary || item.capability_name) + '</p><div class="tags">' + tag(form) + (item.activation_state === 'USED' ? tag('已实际使用','positive') : '') + (item.activation_state === 'BLOCKED_HUMAN' ? tag('等待你的决定','attention') : '') + '</div><button class="copy" data-copy="' + esc(ask) + '">复制调用语句</button><details class="details"><summary>查看详情 ›</summary><dl><dt>适合场景</dt><dd>' + esc((item.when_to_use || []).join('；')) + '</dd><dt>能力增加</dt><dd>' + esc(item.capability_delta) + '</dd><dt>限制</dt><dd>' + esc((item.main_limitations || []).join('；')) + '</dd><dt>来源仓库</dt><dd><a href="' + esc(item.url || '#') + '" target="_blank" rel="noreferrer">' + esc(item.repository) + '</a></dd><dt>技术状态</dt><dd class="machine">' + esc(item.activation_state) + ' / ' + esc(item.activation_tier) + ' / ' + esc(item.semantic_action) + '</dd></dl></details></article>';
}
function listRow(item, status) { return '<div class="list-row"><div><strong>' + esc(displayName(item.repository)) + '</strong><div class="repo-secondary">' + esc(item.repository || '') + '</div><p>' + esc(item.summary || item.human_summary || item.detail || '') + '</p></div>' + (status ? chip(status, humanStatus(status)) : '<span class="meta">' + esc(date(item.time || item.updated_at)) + '</span>') + '</div>'; }
function renderHome() {
  var s = state.summary || {counts:{},recent_discoveries:[],validating:[],directly_usable_cards:[],knowledge_cards:[],health:{}}; var c = s.counts || {}; var h = s.health || {};
  var recent = (s.recent_discoveries || []).map(function (x) { return listRow({repository:x.repository,summary:x.summary,time:x.time}, null); }).join('');
  var validating = (s.validating || []).map(function (x) { return listRow({repository:x.repository,summary:(x.step || '') + ' · ' + (x.result || '')}, 'QUARANTINE_READY'); }).join('');
  var usable = (s.directly_usable_cards || []).slice(0,4).map(function (x) { return listRow(x, x.activation_state || 'TRIAL_ENABLED'); }).join('');
  var methods = (s.knowledge_cards || []).slice(0,4).map(function (x) { return listRow(x, 'REFERENCE_ONLY'); }).join('');
  var notice = h.issues && h.issues.length ? '<div class="notice"><strong>系统有 ' + h.issues.length + ' 项提醒</strong><span>' + h.issues.map(issueLabel).join('、') + '</span><button class="button inline-action" data-view="system">查看状态</button></div>' : '';
  app.innerHTML = '<div class="hero"><div><div class="eyebrow">PERSONAL TECH INTELLIGENCE</div><h1>技术丞相</h1><p class="subtitle">把后台发现的能力，整理成看得懂、用得上的下一步。</p></div><div class="hero-status">' + chip(s.status || '正常') + '<div class="meta">本页数据 · ' + esc(date(new Date().toISOString())) + '</div></div></div>' + notice + '<div class="grid stats"><div class="stat"><span>能力总数</span><strong>' + (c.total || 0) + '</strong><small>已完成判断</small></div><div class="stat"><span>已实际使用</span><strong>' + (c.used || 0) + '</strong><small>已有真实使用记录</small></div><div class="stat"><span>知识库 / 方法</span><strong>' + (c.active_patterns || 0) + '</strong><small>可供参考</small></div><div class="stat"><span>正在验证</span><strong>' + (c.validating || 0) + '</strong><small>隔离观察中</small></div><div class="stat"><span>需要你决定</span><strong>' + (c.human_gated || 0) + '</strong><small>不会自动启用</small></div><div class="stat"><span>暂不采用</span><strong>' + (c.not_adopted || 0) + '</strong><small>保留判断记录</small></div></div><div class="two-col"><section class="panel"><div class="section-head"><div><h2>最近发现</h2><p class="section-note">后台最新进入判断库的项目</p></div><button class="button" data-view="activity">查看全部</button></div>' + (recent || empty('还没有发现任何能力。')) + '</section><section class="panel"><div class="section-head"><div><h2>正在验证</h2><p class="section-note">只展示当前有动作的项目</p></div><button class="button" data-view="system">系统状态</button></div>' + (validating || empty('当前没有正在验证的能力。')) + '</section></div><div class="two-col"><section class="panel"><div class="section-head"><div><h2>已实际使用</h2><p class="section-note">有真实使用记录的能力</p></div><button class="button" data-view="capabilities">能力库</button></div>' + (usable || empty('还没有已投入使用的能力。')) + '</section><section class="panel"><div class="section-head"><div><h2>知识库 / 方法参考</h2><p class="section-note">适合比较、借鉴与设计参考</p></div><button class="button" data-view="capabilities">查看能力库</button></div>' + (methods || empty('当前没有方法参考。')) + '</section></div>';
}
function renderCapabilities() {
  var routes = {}; state.capabilities.forEach(function (x) { routes[x.best_route] = true; });
  app.innerHTML = '<div class="page-head"><div><div class="eyebrow">CAPABILITY LIBRARY</div><h1>能力库</h1><p class="subtitle">按最近更新时间浏览所有已判断能力。仓库只是来源，能力本身才是重点。</p></div><div class="page-count"><strong>' + state.capabilities.length + '</strong><span>项能力</span></div></div><div class="filters"><label class="search-field"><span>⌕</span><input id="cap-search" placeholder="搜索能力名称、用途或仓库" aria-label="搜索能力"></label><select id="cap-status" aria-label="按状态筛选"><option value="">全部状态</option><option value="TRIAL_ENABLED">可直接使用</option><option value="USED">已实际使用</option><option value="REFERENCE_ONLY">知识库 / 方法参考</option><option value="QUARANTINE_READY">正在验证</option><option value="BLOCKED_HUMAN">需要你决定</option><option value="NOT_ADOPTED">暂未采用</option></select><select id="cap-route" aria-label="按类别筛选"><option value="">全部类别</option>' + Object.keys(routes).map(function (x) { return '<option value="' + esc(x) + '">' + esc(category(x)) + '</option>'; }).join('') + '</select><span id="filter-count" class="filter-count"></span></div><div id="cap-list" class="cap-grid">' + (state.capabilities.length ? state.capabilities.map(capabilityCard).join('') : empty('还没有能力记录。')) + '</div>';
  document.querySelector('#cap-search').addEventListener('input', filterCapabilities); document.querySelector('#cap-status').addEventListener('change', filterCapabilities); document.querySelector('#cap-route').addEventListener('change', filterCapabilities); filterCapabilities();
}
function filterCapabilities() { var q = document.querySelector('#cap-search').value.toLowerCase(); var status = document.querySelector('#cap-status').value; var route = document.querySelector('#cap-route').value; var list = state.capabilities.filter(function (x) { var normalized = x.activation_state === 'USED' ? 'USED' : x.activation_state === 'TRIAL_ENABLED' ? 'TRIAL_ENABLED' : (x.activation_state === 'REFERENCE_ONLY' || x.activation_state === 'ACTIVE_PATTERN' ? 'REFERENCE_ONLY' : x.activation_state); return (!q || (displayName(x.repository) + ' ' + JSON.stringify(x)).toLowerCase().indexOf(q) >= 0) && (!status || normalized === status) && (!route || x.best_route === route); }); document.querySelector('#filter-count').textContent = list.length + ' 项'; document.querySelector('#cap-list').innerHTML = list.length ? list.map(capabilityCard).join('') : empty('没有符合条件的能力。'); }
function renderActivity() { var list = state.activity.map(function (x) { return '<div class="timeline-row"><span class="timeline-dot ' + statusClass(x.machine_status) + '" aria-hidden="true"></span><div class="timeline-content"><strong>' + esc(x.title) + (x.repository ? ' · ' + esc(displayName(x.repository)) : '') + '</strong><p>' + esc(x.detail) + '</p><div class="machine">内部记录：' + esc(x.machine_status || '') + '</div></div><div class="timeline-side">' + chip(x.machine_status, x.status || humanStatus(x.machine_status)) + '<time>' + esc(date(x.time)) + '</time></div></div>'; }).join(''); app.innerHTML = '<div class="page-head"><div><div class="eyebrow">ACTIVITY LOG</div><h1>最近动态</h1><p class="subtitle">Radar、Chancellor 和能力状态的时间线。</p></div></div><section class="panel timeline">' + (list || empty('还没有动态记录。')) + '</section>'; }
function renderSystem() { var h = state.summary && state.summary.health || {}; var tasks = (h.tasks || []).map(function (x) { return '<div class="list-row"><div><strong>计划任务</strong><p>' + esc(x.name) + '</p></div><span class="machine">' + esc(humanStatus(x.last_result || 'UNKNOWN')) + '</span></div>'; }).join(''); var scan = h.latest_scan_run || {}; var stage = h.latest_stage_b_run || {}; app.innerHTML = '<div class="page-head"><div><div class="eyebrow">RUNTIME HEALTH</div><h1>系统状态</h1><p class="subtitle">这里展示后台已有的运行观察结果，不改变原始判断。</p></div>' + chip(state.summary && state.summary.status || '正常') + '</div><div class="grid stats compact-stats"><div class="stat"><span>等待处理</span><strong>' + (h.active_pending || 0) + '</strong><small>待丞相判断</small></div><div class="stat"><span>判断记录</span><strong>' + (h.decision_history_count || 0) + '</strong><small>已留存</small></div><div class="stat"><span>涉及项目</span><strong>' + (h.unique_decision_repositories || 0) + '</strong><small>不同仓库</small></div></div><section class="panel"><div class="section-head"><div><h2>后台组件</h2><p class="section-note">最近一次运行概览</p></div></div><div class="list"><div class="list-row"><div><strong>Radar · 项目发现</strong><p>最近运行：' + esc(date(scan.started_at)) + '</p></div>' + chip(scan.status || '暂无运行') + '</div><div class="list-row"><div><strong>Chancellor · 项目判断</strong><p>最近处理：' + esc(date(stage.started_at)) + '</p></div>' + chip(stage.status || '暂无运行') + '</div>' + tasks + '</div></section>' + (h.issues && h.issues.length ? '<section class="panel"><div class="section-head"><div><h2>需要注意</h2><p class="section-note">这些提醒不等于能力数据丢失</p></div></div>' + h.issues.map(function (x) { return '<div class="notice notice-row"><span>' + esc(issueLabel(x)) + '</span><details><summary>技术详情</summary><span class="machine">' + esc(x) + '</span></details></div>'; }).join('') + '</section>' : ''); }
function renderDocuments() { var list = state.documents.map(function (x) { return '<div class="document-row"><div><a class="document-link" data-document="' + esc(x.path) + '">' + esc(x.title) + '</a><div class="repo-secondary">' + esc(x.path) + '</div></div><span class="tag">' + esc(x.category || '项目文档') + '</span><span class="meta">' + esc(date(x.modified)) + '</span></div>'; }).join(''); app.innerHTML = '<div class="page-head"><div><div class="eyebrow">PROJECT LIBRARY</div><h1>文档</h1><p class="subtitle">项目文档和报告索引。点击后在本地安全阅读。</p></div><div class="page-count"><strong>' + state.documents.length + '</strong><span>份文档</span></div></div><section class="panel document-library">' + (list || empty('还没有可展示的项目文档。')) + '</section>'; document.querySelectorAll('[data-document]').forEach(function (node) { node.addEventListener('click', function () { openDocument(node.dataset.document); }); }); }
function openDocument(path) { getJSON('/api/document?path=' + encodeURIComponent(path)).then(function (doc) { app.innerHTML = '<div class="page-head"><div><button class="button" data-view="documents">‹ 返回文档</button><div class="eyebrow">DOCUMENT READER</div><h1>' + esc(doc.title || path) + '</h1><p class="repo-secondary">' + esc(path) + '</p></div></div><section class="panel markdown">' + doc.html + '</section>'; }); }
function render() { if (state.view === 'home') renderHome(); if (state.view === 'capabilities') renderCapabilities(); if (state.view === 'activity') renderActivity(); if (state.view === 'system') renderSystem(); if (state.view === 'documents') renderDocuments(); }
function applyTheme(value) { if (value === 'system') document.documentElement.removeAttribute('data-theme'); else document.documentElement.setAttribute('data-theme', value); localStorage.setItem('techchancellor-theme', value); }
function initTheme() { var select = document.querySelector('#theme-select'); var saved = localStorage.getItem('techchancellor-theme') || 'system'; select.value = saved; applyTheme(saved); select.addEventListener('change', function () { applyTheme(select.value); }); }
function updateHealth() { var h = state.summary && state.summary.health || {}; var node = document.querySelector('#global-health'); if (!node) return; var count = (h.issues || []).length; node.textContent = count ? '● ' + count + ' 项提醒' : '● 系统正常'; node.className = 'health-indicator ' + (count ? 'has-warning' : 'is-ok'); }
function load() { Promise.all([getJSON('/api/summary'), getJSON('/api/capabilities'), getJSON('/api/activity'), getJSON('/api/documents')]).then(function (values) { state.summary = values[0]; state.capabilities = values[1].items || []; state.activity = values[2].items || []; state.documents = values[3].items || []; document.querySelector('#last-refresh').textContent = '更新于 ' + new Date().toLocaleTimeString('zh-CN', {hour12:false}); updateHealth(); render(); }).catch(function (error) { app.innerHTML = '<div class="notice">控制台连接失败：' + esc(error.message) + '。请确认本地服务仍在运行。</div>'; }); }
document.addEventListener('click', function (event) { var target = event.target.closest('[data-view]'); if (target) { state.view = target.dataset.view; document.querySelectorAll('.nav-item').forEach(function (item) { item.classList.toggle('active', item.dataset.view === state.view); }); render(); } var copy = event.target.closest('[data-copy]'); if (copy && navigator.clipboard) navigator.clipboard.writeText(copy.dataset.copy).then(function () { copy.textContent = '已复制'; setTimeout(function () { copy.textContent = '复制调用语句'; }, 1200); }); });
document.querySelector('[data-action=refresh]').addEventListener('click', load); initTheme(); load();
