var state = { summary: null, view: 'home', capabilities: [], documents: [], activity: [] };
var app = document.querySelector('#app');
function esc(value) { return String(value == null ? '' : value).replace(/[&<>"']/g, function (c) { return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]; }); }
function date(value) { return value ? new Date(value).toLocaleString('zh-CN', {hour12:false}) : '暂无'; }
function chip(status) { var cls = status === '正常' ? 'ok' : status === '异常' ? 'bad' : 'warn'; return '<span class="status-chip ' + cls + '">' + esc(status || '暂无') + '</span>'; }
function empty(text) { return '<div class="empty">' + esc(text) + '</div>'; }
function getJSON(url) { return fetch(url, {cache:'no-store'}).then(function (r) { if (!r.ok) throw new Error(r.statusText); return r.json(); }); }
function capabilityCard(item) {
  var ask = (item.how_to_ask_codex || [])[0] || '直接描述你的目标，Codex 会判断是否相关。';
  return '<article class="card"><div class="card-head"><div><h3><a href="' + esc(item.url || '#') + '" target="_blank" rel="noreferrer">' + esc(item.repository) + '</a></h3><div class="meta">' + esc(item.best_route || 'GENERAL') + ' · ' + esc(date(item.updated_at)) + '</div></div>' + chip(item.lifecycle_status) + '</div><p>' + esc(item.human_summary || item.capability_name) + '</p><div class="tags"><span class="tag">' + esc(item.consumption_form) + '</span><span class="tag">' + esc(item.evidence_maturity) + '</span>' + (item.activation_state === 'USED' ? '<span class="tag">已实际使用</span>' : '') + '</div><button class="copy" data-copy="' + esc(ask) + '">复制调用语句</button><details class="details"><summary>查看详情</summary><dl><dt>适合场景</dt><dd>' + esc((item.when_to_use || []).join('；')) + '</dd><dt>能力增加</dt><dd>' + esc(item.capability_delta) + '</dd><dt>限制</dt><dd>' + esc((item.main_limitations || []).join('；')) + '</dd><dt>技术状态</dt><dd class="machine">' + esc(item.activation_state) + ' / ' + esc(item.activation_tier) + ' / ' + esc(item.semantic_action) + '</dd></dl></details></article>';
}
function renderHome() {
  var s = state.summary || {counts:{},recent_discoveries:[],validating:[],directly_usable_cards:[],knowledge_cards:[],health:{}}; var c = s.counts || {}; var h = s.health || {};
  var recent = (s.recent_discoveries || []).map(function (x) { return '<div class="list-row"><div><strong>' + esc(x.repository) + '</strong><p>' + esc(x.summary) + '</p><div class="meta">' + esc(x.source) + ' · ' + esc(x.stage) + '</div></div><span class="meta">' + esc(date(x.time)) + '</span></div>'; }).join('');
  var validating = (s.validating || []).map(function (x) { return '<div class="list-row"><div><strong>' + esc(x.repository) + '</strong><p>' + esc(x.step) + ' · ' + esc(x.result) + '</p></div><span class="tag">' + esc(x.risk) + '</span></div>'; }).join('');
  var usable = (s.directly_usable_cards || []).slice(0,4).map(function (x) { return '<div class="list-row"><div><strong>' + esc(x.repository) + '</strong><p>' + esc(x.human_summary) + '</p><div class="meta">' + esc((x.how_to_ask_codex || [])[0] || '') + '</div></div>' + chip(x.lifecycle_status) + '</div>'; }).join('');
  var methods = (s.knowledge_cards || []).slice(0,4).map(function (x) { return '<div class="list-row"><div><strong>' + esc(x.repository) + '</strong><p>' + esc(x.human_summary) + '</p></div><span class="tag">方法参考</span></div>'; }).join('');
  app.innerHTML = '<div class="hero"><div><h1>技术丞相</h1><p class="subtitle">让后台发现的能力，变成人看得懂的下一步。</p></div><div class="hero-status">' + chip(s.status || '正常') + '<div class="meta">最近刷新：' + esc(date(new Date().toISOString())) + '</div></div></div>' + (h.issues && h.issues.length ? '<div class="notice">系统需要注意：' + esc(h.issues.join('、')) + '。这是运行观察，不代表能力数据丢失。</div>' : '') + '<div class="grid stats"><div class="stat"><span>能力总数</span><strong>' + (c.total || 0) + '</strong></div><div class="stat"><span>已投入使用</span><strong>' + (c.used || 0) + '</strong></div><div class="stat"><span>已启用方法</span><strong>' + (c.active_patterns || 0) + '</strong></div><div class="stat"><span>正在验证</span><strong>' + (c.validating || 0) + '</strong></div><div class="stat"><span>需要决定</span><strong>' + (c.human_gated || 0) + '</strong></div><div class="stat"><span>暂不采用</span><strong>' + (c.not_adopted || 0) + '</strong></div></div><div class="two-col"><section class="panel"><div class="section-head"><h2>最近发现</h2><button class="button" data-view="activity">查看全部</button></div>' + (recent || empty('还没有发现任何能力。')) + '</section><section class="panel"><div class="section-head"><h2>正在验证</h2><button class="button" data-view="system">系统状态</button></div>' + (validating || empty('当前没有正在验证的能力。')) + '</section></div><div class="two-col"><section class="panel"><div class="section-head"><h2>已投入使用</h2><button class="button" data-view="capabilities">能力库</button></div>' + (usable || empty('还没有已投入使用的能力。')) + '</section><section class="panel"><div class="section-head"><h2>知识库 / 方法参考</h2><button class="button" data-view="capabilities">查看能力库</button></div>' + (methods || empty('当前没有方法参考。')) + '</section></div>';
}
function renderCapabilities() {
  var routes = {}; state.capabilities.forEach(function (x) { routes[x.best_route] = true; });
  app.innerHTML = '<div class="page-head"><div><h1>能力库</h1><p class="subtitle">所有已判断能力，按最近更新时间排列。</p></div></div><div class="filters"><input id="cap-search" placeholder="搜索名称、用途或仓库"><select id="cap-status"><option value="">全部状态</option><option>已安装，可使用</option><option>已实际使用</option><option>知识库 / 方法参考</option><option>正在验证</option><option>需要人工决定</option><option>已研究，暂不采用</option></select><select id="cap-route"><option value="">全部类别</option>' + Object.keys(routes).map(function (x) { return '<option>' + esc(x) + '</option>'; }).join('') + '</select></div><div id="cap-list" class="cap-grid">' + (state.capabilities.length ? state.capabilities.map(capabilityCard).join('') : empty('还没有能力记录。')) + '</div>';
  document.querySelector('#cap-search').addEventListener('input', filterCapabilities); document.querySelector('#cap-status').addEventListener('change', filterCapabilities); document.querySelector('#cap-route').addEventListener('change', filterCapabilities);
}
function filterCapabilities() { var q = document.querySelector('#cap-search').value.toLowerCase(); var status = document.querySelector('#cap-status').value; var route = document.querySelector('#cap-route').value; var list = state.capabilities.filter(function (x) { return (!q || JSON.stringify(x).toLowerCase().indexOf(q) >= 0) && (!status || x.lifecycle_status === status) && (!route || x.best_route === route); }); document.querySelector('#cap-list').innerHTML = list.length ? list.map(capabilityCard).join('') : empty('没有符合条件的能力。'); }
function renderActivity() { var list = state.activity.map(function (x) { return '<div class="list-row"><div><strong>' + esc(x.title) + (x.repository ? ' · ' + esc(x.repository) : '') + '</strong><p>' + esc(x.detail) + '</p></div><div class="meta">' + esc(date(x.time)) + '<br>' + esc(x.status) + '</div></div>'; }).join(''); app.innerHTML = '<div class="page-head"><div><h1>最近动态</h1><p class="subtitle">Radar、Chancellor 和能力状态的时间线。</p></div></div><section class="panel">' + (list || empty('还没有动态记录。')) + '</section>'; }
function renderSystem() { var h = state.summary && state.summary.health || {}; var tasks = (h.tasks || []).map(function (x) { return '<div class="list-row"><div><strong>计划任务</strong><p>' + esc(x.name) + '</p></div><span class="machine">' + esc(x.last_result || 'UNKNOWN') + '</span></div>'; }).join(''); app.innerHTML = '<div class="page-head"><div><h1>系统状态</h1><p class="subtitle">这里复用后台已有 health 语义，不建立第二套健康判断。</p></div>' + chip(state.summary && state.summary.status || '正常') + '</div><div class="grid stats"><div class="stat"><span>等待处理</span><strong>' + (h.active_pending || 0) + '</strong></div><div class="stat"><span>判断记录</span><strong>' + (h.decision_history_count || 0) + '</strong></div><div class="stat"><span>不同项目</span><strong>' + (h.unique_decision_repositories || 0) + '</strong></div></div><section class="panel"><h2>后台组件</h2><div class="list"><div class="list-row"><div><strong>Radar</strong><p>最近运行：' + esc(date(h.latest_scan_run && h.latest_scan_run.started_at)) + '</p></div>' + chip(h.latest_scan_run && h.latest_scan_run.status || '暂无运行') + '</div><div class="list-row"><div><strong>Chancellor</strong><p>最近处理：' + esc(date(h.latest_stage_b_run && h.latest_stage_b_run.started_at)) + '</p></div>' + chip(h.latest_stage_b_run && h.latest_stage_b_run.status || '暂无运行') + '</div>' + tasks + '</div></section>' + (h.issues && h.issues.length ? '<section class="panel"><h2>需要注意</h2>' + h.issues.map(function (x) { return '<p class="notice">' + esc(x) + '：详细机器状态仅作展开参考。</p>'; }).join('') + '</section>' : ''); }
function renderDocuments() { var list = state.documents.map(function (x) { return '<div class="document-row"><a class="document-link" data-document="' + esc(x.path) + '">' + esc(x.title) + '</a><span class="tag">' + esc(x.category) + '</span><span class="meta">' + esc(date(x.modified)) + '</span></div>'; }).join(''); app.innerHTML = '<div class="page-head"><div><h1>文档</h1><p class="subtitle">项目文档和报告索引。点击后在本地浏览器中安全渲染。</p></div></div><section class="panel">' + (list || empty('还没有可展示的项目文档。')) + '</section>'; document.querySelectorAll('[data-document]').forEach(function (node) { node.addEventListener('click', function () { openDocument(node.dataset.document); }); }); }
function openDocument(path) { getJSON('/api/document?path=' + encodeURIComponent(path)).then(function (doc) { app.innerHTML = '<div class="page-head"><div><button class="button" data-view="documents">返回文档</button><h1>' + esc(path) + '</h1></div></div><section class="panel markdown">' + doc.html + '</section>'; }); }
function render() { if (state.view === 'home') renderHome(); if (state.view === 'capabilities') renderCapabilities(); if (state.view === 'activity') renderActivity(); if (state.view === 'system') renderSystem(); if (state.view === 'documents') renderDocuments(); }
function load() { Promise.all([getJSON('/api/summary'), getJSON('/api/capabilities'), getJSON('/api/activity'), getJSON('/api/documents')]).then(function (values) { state.summary = values[0]; state.capabilities = values[1].items || []; state.activity = values[2].items || []; state.documents = values[3].items || []; document.querySelector('#last-refresh').textContent = '已更新 ' + new Date().toLocaleTimeString('zh-CN'); render(); }).catch(function (error) { app.innerHTML = '<div class="notice">控制台连接失败：' + esc(error.message) + '。请确认本地服务仍在运行。</div>'; }); }
document.addEventListener('click', function (event) { var target = event.target.closest('[data-view]'); if (target) { state.view = target.dataset.view; document.querySelectorAll('.nav-item').forEach(function (item) { item.classList.toggle('active', item.dataset.view === state.view); }); render(); } var copy = event.target.closest('[data-copy]'); if (copy && navigator.clipboard) navigator.clipboard.writeText(copy.dataset.copy).then(function () { copy.textContent = '已复制'; setTimeout(function () { copy.textContent = '复制调用语句'; }, 1200); }); });
document.querySelector('[data-action=refresh]').addEventListener('click', load); load();
