var state = { summary: null, view: 'home', capabilities: [], documents: [], activity: [], detailId: null };
var app = document.querySelector('#app');
var VIEW_LABELS = {home:'总览',capabilities:'能力库',activity:'最近动态',system:'系统状态',documents:'文档'};
var NAME_MAP = {'tt-a1i/archify':'Archify','github/spec-kit':'Spec Kit','bmad-code-org/BMAD-METHOD':'BMAD Method','langchain-ai/langchain':'LangChain','coleam00/archon':'Archon','TauricResearch/TradingAgents':'TradingAgents','nieledran/backtesting-engine':'backtesting-engine'};
var CATEGORY_MAP = {'AI_AGENT':'AI / 智能体','AI_EXPERIENCE':'AI / 体验','QUANT_DATA':'量化 / 数据','WATCHLIST':'观察清单','DEVELOPER_TOOL':'开发工具','KNOWLEDGE':'知识与方法','GENERAL':'其他'};
var STATUS_MAP = {'USED':'已实际使用','TRIAL_ENABLED':'可直接使用','ACTIVE_PATTERN':'知识库 / 方法参考','REFERENCE_ONLY':'知识库 / 方法参考','QUARANTINE_READY':'正在验证','CANDIDATE_FOR_QUARANTINE':'进入验证','BLOCKED_HUMAN':'需要你决定','FAILED_VALIDATION':'暂未采用','NOT_ADOPTED':'暂未采用','REVIEWED':'已完成判断','SCAN_SUCCESS':'扫描完成','SCAN_NOT_EVALUATED':'扫描需要注意','CHANCELLOR_SUCCESS':'处理完成','CHANCELLOR_SUCCESS_NO_PENDING':'处理完成，无待办','RUNNING':'运行中','COMPLETED':'已完成','SUCCESS':'正常','DEGRADED_HISTORY_ONLY':'有历史提醒','NOT_EVALUATED':'需要注意'};

function esc(value) { return String(value == null ? '' : value).replace(/[&<>"']/g, function (c) { return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]; }); }
function date(value, technical) { if (!value) return '暂无'; var d = new Date(value); if (isNaN(d.getTime())) return String(value); return d.toLocaleString('zh-CN', technical ? {hour12:false} : {year:'numeric',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}); }
function displayName(repo) { return NAME_MAP[repo] || String(repo || '未命名能力').split('/').pop().replace(/[-_]+/g, ' '); }
function category(value) { return CATEGORY_MAP[value] || String(value || '其他').replace(/_/g, ' '); }
function humanStatus(value) { return STATUS_MAP[value] || String(value || '暂无').replace(/_/g, ' '); }
function statusClass(value) { var s = String(value || ''); if (s === 'USED' || s === 'TRIAL_ENABLED' || s === 'SUCCESS' || s === '正常') return 'ok'; if (s.indexOf('FAIL') >= 0 || s.indexOf('NOT_ADOPTED') >= 0 || s === '异常' || s === 'NOT_EVALUATED') return 'bad'; if (s.indexOf('BLOCKED') >= 0 || s.indexOf('DEGRADED') >= 0 || s.indexOf('NEED') >= 0 || s.indexOf('提醒') >= 0) return 'warn'; if (s.indexOf('QUARANTINE') >= 0 || s.indexOf('CANDIDATE') >= 0 || s === 'RUNNING') return 'info'; return 'neutral'; }
function chip(value, label) { return '<span class="status-chip ' + statusClass(value) + '"><span class="status-dot" aria-hidden="true"></span>' + esc(label || humanStatus(value)) + '</span>'; }
function tag(label, cls) { return '<span class="tag ' + (cls || '') + '">' + esc(label) + '</span>'; }
function getJSON(url) { return fetch(url, {cache:'no-store'}).then(function (response) { if (!response.ok) throw new Error(response.statusText); return response.json(); }); }
function issueLabel(value) { return {'ACTIVE_PENDING_PACKETS':'有待处理内容','TASK_LAST_RESULT_NONZERO':'计划任务存在历史提醒','STALE_OR_MALFORMED_LOCK':'后台锁需要检查','INCOMPLETE_SCAN_RUN':'存在未完成扫描记录'}[value] || humanStatus(value); }
function formLabel(item) { return item.consumption_form === 'TOOL' ? '可调用工具' : item.consumption_form === 'PATTERN' ? '方法参考' : '知识参考'; }
function primaryStatusLabel(item) { if (item.activation_state === 'BLOCKED_HUMAN') return '需要你决定'; if (item.activation_state === 'FAILED_VALIDATION' || item.activation_state === 'NOT_ADOPTED') return '暂未采用'; return item.lifecycle_status || humanStatus(item.activation_state); }
function taskResultLabel(value) { if (value === 0 || value === '0') return '上次运行正常'; if (value == null || value === '') return '暂无运行记录'; return '上次运行需检查'; }
function collectionReason(item) { if (item.review_reason === 'USER_REQUESTED') return '这是你明确要求研究的项目。完成评估和隔离验证后，TechChancellor 将它保留为可复用能力。'; if (item.activation_state === 'USED') return '它已经在真实任务中使用过，因此保留在能力库中，供相似任务直接调用。'; if (item.activation_state === 'ACTIVE_PATTERN' || item.activation_state === 'REFERENCE_ONLY') return '它提供了可复用的设计思路和方法参考，适合在相似任务中比较和借鉴。'; if (item.activation_state === 'BLOCKED_HUMAN') return '它可能带来新的能力，但是否采用仍需要你的明确决定，系统不会自动启用。'; return 'TechChancellor 已完成项目判断并保留记录，便于后续追踪和重新评估。'; }
function quietState(title, detail) { return '<div class="quiet-state"><span class="quiet-mark">✓</span><div><strong>' + esc(title) + '</strong><p>' + esc(detail) + '</p></div></div>'; }
function viewHeader(kicker, title, subtitle, extra) { return '<div class="page-head"><div><span class="kicker">' + esc(kicker) + '</span><h1>' + esc(title) + '</h1><p>' + esc(subtitle) + '</p></div>' + (extra || '') + '</div>'; }
function bulletList(items, emptyText) { var values = (items || []).filter(Boolean); return values.length ? '<ul class="clean-list">' + values.map(function (item) { return '<li>' + esc(item) + '</li>'; }).join('') + '</ul>' : '<p class="muted">' + esc(emptyText) + '</p>'; }

function capabilityCard(item) {
  return '<article class="capability-card"><button class="card-open" data-capability-id="' + esc(item.repository) + '" aria-label="查看 ' + esc(displayName(item.repository)) + ' 详情"></button><div class="card-top"><span class="capability-monogram">' + esc(displayName(item.repository).charAt(0).toUpperCase()) + '</span>' + chip(item.activation_state || item.lifecycle_status, primaryStatusLabel(item)) + '</div><div class="card-title"><h3>' + esc(displayName(item.repository)) + '</h3><span>' + esc(item.repository || '') + '</span></div><p>' + esc(item.human_summary || item.capability_name) + '</p><div class="card-foot"><span>' + esc(category(item.best_route)) + '</span><span>' + esc(formLabel(item)) + '</span><strong>查看详情 →</strong></div></article>';
}

function listRow(item, status) { return '<div class="compact-row"><div class="compact-symbol">' + esc(displayName(item.repository).charAt(0).toUpperCase()) + '</div><div class="compact-copy"><strong>' + esc(displayName(item.repository)) + '</strong><span>' + esc(item.repository || '') + '</span><p>' + esc(item.summary || item.human_summary || item.detail || '') + '</p></div>' + (status ? chip(status, humanStatus(status)) : '<time>' + esc(date(item.time || item.updated_at)) + '</time>') + '</div>'; }

function renderHome() {
  var s = state.summary || {counts:{},recent_discoveries:[],validating:[],directly_usable_cards:[],knowledge_cards:[],health:{}};
  var c = s.counts || {}; var h = s.health || {}; var issueCount = (h.issues || []).length;
  var recent = (s.recent_discoveries || []).slice(0,5).map(function (x) { return listRow({repository:x.repository,summary:x.summary,time:x.time}); }).join('');
  var validating = (s.validating || []).slice(0,3).map(function (x) { return listRow({repository:x.repository,summary:(x.step || '') + ' · ' + (x.result || '')}, 'QUARANTINE_READY'); }).join('');
  var featured = (s.directly_usable_cards || []).concat(s.knowledge_cards || []).slice(0,4).map(function (x) { return '<button class="mini-capability" data-capability-id="' + esc(x.repository) + '"><span class="mini-mark">' + esc(displayName(x.repository).charAt(0).toUpperCase()) + '</span><span><strong>' + esc(displayName(x.repository)) + '</strong><small>' + esc(x.lifecycle_status) + '</small></span><b>→</b></button>'; }).join('');
  var validationPanel = validating || quietState('当前没有验证任务','系统处于安静状态；新项目进入隔离验证后会显示在这里。');
  var healthCopy = issueCount ? issueCount + ' 项运行提醒' : '后台运行正常';
  var healthDetail = issueCount ? (h.issues || []).map(issueLabel).join('、') : '没有需要你处理的异常或阻塞。';
  app.innerHTML = viewHeader('今日总览','技术丞相','项目发现、能力判断与本地知识库的统一入口。','<div class="day-status ' + (issueCount ? 'warn' : 'ok') + '"><span class="pulse-dot"></span><div><strong>' + esc(healthCopy) + '</strong><small>' + esc(date(new Date().toISOString())) + '</small></div></div>') +
    '<div class="overview-grid"><section class="overview-main surface"><div class="overview-lead"><div><span class="section-label">能力资产</span><strong>' + (c.total || 0) + '</strong><p>项能力已经完成判断并进入本地能力库</p></div><button class="primary-button" data-view="capabilities">打开能力库 <span>→</span></button></div><div class="metric-strip"><div><strong>' + (c.used || 0) + '</strong><span>已实际使用</span></div><div><strong>' + (c.active_patterns || 0) + '</strong><span>知识与方法</span></div><div><strong>' + (c.validating || 0) + '</strong><span>正在验证</span></div><div><strong>' + (c.human_gated || 0) + '</strong><span>需要决定</span></div></div><div class="section-head"><div><h2>最近发现</h2><p>最新进入判断范围的项目</p></div><button class="text-button" data-view="activity">全部动态 →</button></div><div class="compact-list">' + (recent || quietState('尚无发现记录','下一次 Radar 扫描完成后会在这里出现。')) + '</div></section><aside class="overview-side"><section class="status-surface ' + (issueCount ? 'has-warning' : '') + '"><span class="section-label">系统状态</span><h2>' + esc(healthCopy) + '</h2><p>' + esc(healthDetail) + '</p><button class="text-button" data-view="system">查看运行详情 →</button></section><section class="surface validation-surface"><div class="section-head"><div><h2>正在验证</h2><p>隔离环境中的能力</p></div></div>' + validationPanel + '</section></aside></div><section class="surface capability-shelf"><div class="section-head"><div><h2>随时可取用</h2><p>已使用能力与高价值方法</p></div><button class="text-button" data-view="capabilities">浏览全部 →</button></div><div class="mini-grid">' + (featured || quietState('能力库正在建立','完成首次判断后，可用能力会出现在这里。')) + '</div></section>';
}

function renderCapabilities() {
  var routes = {}; state.capabilities.forEach(function (item) { routes[item.best_route] = true; });
  app.innerHTML = viewHeader('能力资产','能力库','按用途和成熟度浏览 TechChancellor 已判断的能力。','<div class="page-count"><strong>' + state.capabilities.length + '</strong><span>项已收录</span></div>') + '<div class="library-toolbar"><label class="search-field"><span>⌕</span><input id="cap-search" placeholder="搜索能力、用途或仓库" aria-label="搜索能力"></label><select id="cap-status" aria-label="按状态筛选"><option value="">全部状态</option><option value="TRIAL_ENABLED">可直接使用</option><option value="USED">已实际使用</option><option value="REFERENCE_ONLY">知识库 / 方法参考</option><option value="QUARANTINE_READY">正在验证</option><option value="BLOCKED_HUMAN">需要你决定</option><option value="NOT_ADOPTED">暂未采用</option></select><select id="cap-route" aria-label="按类别筛选"><option value="">全部类别</option>' + Object.keys(routes).map(function (route) { return '<option value="' + esc(route) + '">' + esc(category(route)) + '</option>'; }).join('') + '</select><span id="filter-count" class="filter-count"></span></div><div id="cap-list" class="capability-grid"></div>';
  document.querySelector('#cap-search').addEventListener('input', filterCapabilities);
  document.querySelector('#cap-status').addEventListener('change', filterCapabilities);
  document.querySelector('#cap-route').addEventListener('change', filterCapabilities);
  filterCapabilities();
}

function normalizedState(item) { if (item.activation_state === 'ACTIVE_PATTERN' || item.activation_state === 'REFERENCE_ONLY') return 'REFERENCE_ONLY'; return item.activation_state; }
function filterCapabilities() { var q = document.querySelector('#cap-search').value.toLowerCase(); var status = document.querySelector('#cap-status').value; var route = document.querySelector('#cap-route').value; var list = state.capabilities.filter(function (item) { return (!q || (displayName(item.repository) + ' ' + JSON.stringify(item)).toLowerCase().indexOf(q) >= 0) && (!status || normalizedState(item) === status) && (!route || item.best_route === route); }); document.querySelector('#filter-count').textContent = list.length + ' 项'; document.querySelector('#cap-list').innerHTML = list.length ? list.map(capabilityCard).join('') : quietState('没有符合条件的能力','调整搜索内容或筛选条件后再试。'); }

function renderCapabilityDetail(item) {
  var ask = (item.how_to_ask_codex || [])[0] || '直接描述你的目标，Codex 会判断是否适合使用这项能力。';
  var events = state.activity.filter(function (event) { return event.repository === item.repository; }).slice(0,6);
  var eventHtml = events.map(function (event) { return '<div class="history-row"><span class="timeline-dot ' + statusClass(event.machine_status) + '"></span><div><strong>' + esc(event.title) + '</strong><p>' + esc(event.detail) + '</p><time>' + esc(date(event.time)) + '</time></div></div>'; }).join('');
  state.detailId = item.repository;
  document.querySelector('#current-view-label').textContent = '能力详情';
  app.innerHTML = '<div class="breadcrumb"><button data-view="capabilities">能力库</button><span>›</span><strong>' + esc(displayName(item.repository)) + '</strong></div><section class="detail-hero"><div class="detail-identity"><span class="detail-monogram">' + esc(displayName(item.repository).charAt(0).toUpperCase()) + '</span><div><span class="kicker">' + esc(category(item.best_route)) + '</span><h1>' + esc(displayName(item.repository)) + '</h1><p>' + esc(item.repository) + '</p></div></div><div class="detail-status">' + chip(item.activation_state || item.lifecycle_status, primaryStatusLabel(item)) + '<span>更新于 ' + esc(date(item.updated_at)) + '</span></div></section><div class="detail-layout"><div class="detail-main"><section class="detail-section"><span class="section-label">这是什么</span><h2>' + esc(item.human_summary || item.capability_name) + '</h2><p class="detail-copy">' + esc(collectionReason(item)) + '</p></section><section class="detail-section"><span class="section-label">什么时候该用</span>' + bulletList(item.when_to_use, '当前没有额外的适用场景说明。') + '</section><section class="codex-callout"><div><span class="section-label">让 Codex 使用</span><p>' + esc(ask) + '</p></div><button class="copy-button" data-copy="' + esc(ask) + '">复制调用语句</button></section><section class="detail-section"><span class="section-label">限制与边界</span>' + bulletList(item.main_limitations, '当前没有额外限制说明。') + '</section></div><aside class="detail-aside"><section class="aside-card"><span class="section-label">当前可用性</span><h3>' + esc(primaryStatusLabel(item)) + '</h3><dl><div><dt>能力形式</dt><dd>' + esc(formLabel(item)) + '</dd></div><div><dt>适用类别</dt><dd>' + esc(category(item.best_route)) + '</dd></div><div><dt>证据成熟度</dt><dd>' + esc(humanStatus(item.evidence_maturity)) + '</dd></div></dl></section><section class="aside-card"><span class="section-label">来源</span><a class="source-link" href="' + esc(item.url || '#') + '" target="_blank" rel="noreferrer"><strong>GitHub 仓库</strong><span>' + esc(item.repository) + '</span><b>↗</b></a></section></aside></div><section class="surface history-panel"><div class="section-head"><div><h2>过去发生了什么</h2><p>与这项能力相关的本地判断记录</p></div></div><div class="history-list">' + (eventHtml || quietState('暂无单独动态','当前状态来自能力库记录；后续判断会按时间排列在这里。')) + '</div></section><details class="technical-details"><summary>查看技术字段</summary><dl><div><dt>activation_state</dt><dd>' + esc(item.activation_state) + '</dd></div><div><dt>activation_tier</dt><dd>' + esc(item.activation_tier) + '</dd></div><div><dt>semantic_action</dt><dd>' + esc(item.semantic_action) + '</dd></div></dl></details>';
}

function renderActivity() {
  var rows = state.activity.map(function (item) { return '<article class="activity-row"><div class="activity-track"><span class="timeline-dot ' + statusClass(item.machine_status) + '"></span></div><div class="activity-body"><div class="activity-title"><strong>' + esc(item.title) + '</strong>' + (item.repository ? '<button data-repository="' + esc(item.repository) + '">' + esc(displayName(item.repository)) + '</button>' : '') + '</div><p>' + esc(item.detail) + '</p><details><summary>内部记录</summary><span class="machine">' + esc(item.machine_status || '') + '</span></details></div><div class="activity-meta">' + chip(item.machine_status,item.status || humanStatus(item.machine_status)) + '<time>' + esc(date(item.time)) + '</time></div></article>'; }).join('');
  app.innerHTML = viewHeader('运行记录','最近动态','Radar、Chancellor 与能力生命周期的统一时间线。','') + '<section class="surface activity-feed">' + (rows || quietState('当前没有动态','下一次扫描或判断完成后，记录会出现在这里。')) + '</section>';
}

function renderSystem() {
  var h = state.summary && state.summary.health || {}; var issues = h.issues || []; var scan = h.latest_scan_run || {}; var stage = h.latest_stage_b_run || {};
  var tasks = (h.tasks || []).map(function (task) { return '<div class="runtime-row"><span class="runtime-icon">⌁</span><div><strong>计划任务</strong><p>' + esc(task.name) + '</p></div><span class="runtime-result">' + esc(taskResultLabel(task.last_result)) + '</span></div>'; }).join('');
  var issueRows = issues.map(function (issue) { return '<div class="issue-row"><span>!</span><div><strong>' + esc(issueLabel(issue)) + '</strong><p>该提醒来自已有健康检查，不影响能力库读取。</p></div><details><summary>技术字段</summary><span class="machine">' + esc(issue) + '</span></details></div>'; }).join('');
  app.innerHTML = viewHeader('本地运行','系统状态','查看后台是否按预期工作，以及是否有需要关注的事项。',chip(state.summary && state.summary.status || '正常')) + '<div class="system-grid"><section class="surface runtime-panel"><div class="section-head"><div><h2>后台组件</h2><p>最近一次运行情况</p></div></div><div class="runtime-row"><span class="runtime-icon">R</span><div><strong>Radar · 项目发现</strong><p>最近运行 ' + esc(date(scan.started_at)) + '</p></div>' + chip(scan.status || '暂无运行') + '</div><div class="runtime-row"><span class="runtime-icon">C</span><div><strong>Chancellor · 项目判断</strong><p>最近处理 ' + esc(date(stage.started_at)) + '</p></div>' + chip(stage.status || '暂无运行') + '</div>' + tasks + '</section><aside class="system-summary"><div><span>等待处理</span><strong>' + (h.active_pending || 0) + '</strong><small>待判断内容</small></div><div><span>判断记录</span><strong>' + (h.decision_history_count || 0) + '</strong><small>已经留存</small></div><div><span>涉及项目</span><strong>' + (h.unique_decision_repositories || 0) + '</strong><small>不同仓库</small></div></aside></div><section class="surface issue-panel"><div class="section-head"><div><h2>需要注意</h2><p>系统允许没有告警；安静本身就是正常状态</p></div></div>' + (issueRows || quietState('没有需要处理的提醒','Radar、Chancellor 和计划任务都处于预期状态。')) + '</section>';
}

function renderDocuments() {
  var rows = state.documents.map(function (item) { return '<button class="document-row" data-document="' + esc(item.path) + '"><span class="document-glyph">§</span><span class="document-copy"><strong>' + esc(item.title) + '</strong><small>' + esc(item.path) + '</small></span>' + tag(item.category || '项目文档') + '<time>' + esc(date(item.modified)) + '</time><b>→</b></button>'; }).join('');
  app.innerHTML = viewHeader('项目资料','文档','在本地阅读设计记录、运行报告与项目说明。','<div class="page-count"><strong>' + state.documents.length + '</strong><span>份文档</span></div>') + '<section class="surface document-library">' + (rows || quietState('还没有可阅读文档','项目文档进入允许目录后会自动出现在这里。')) + '</section>';
}

function openDocument(path) { getJSON('/api/document?path=' + encodeURIComponent(path)).then(function (doc) { document.querySelector('#current-view-label').textContent = '文档阅读'; app.innerHTML = '<div class="reader-bar"><button class="text-button" data-view="documents">← 返回文档</button><span>' + esc(path) + '</span></div><article class="markdown-reader"><header><span class="kicker">本地文档</span><h1>' + esc(path.split('/').pop()) + '</h1><p>' + esc(path) + '</p></header><div class="markdown">' + doc.html + '</div></article>'; }); }

function setView(view) { state.view = view; state.detailId = null; document.querySelectorAll('.nav-item').forEach(function (item) { item.classList.toggle('active', item.dataset.view === view); }); document.querySelector('#current-view-label').textContent = VIEW_LABELS[view] || '总览'; render(); window.scrollTo(0,0); }
function render() { if (state.view === 'home') renderHome(); if (state.view === 'capabilities') renderCapabilities(); if (state.view === 'activity') renderActivity(); if (state.view === 'system') renderSystem(); if (state.view === 'documents') renderDocuments(); }
function applyTheme(value) { if (value === 'system') document.documentElement.removeAttribute('data-theme'); else document.documentElement.setAttribute('data-theme', value); localStorage.setItem('techchancellor-theme', value); }
function initTheme() { var select = document.querySelector('#theme-select'); var saved = localStorage.getItem('techchancellor-theme') || 'system'; select.value = saved; applyTheme(saved); select.addEventListener('change', function () { applyTheme(select.value); }); }
function updateHealth() { var health = state.summary && state.summary.health || {}; var count = (health.issues || []).length; var node = document.querySelector('#global-health'); node.className = 'rail-health ' + (count ? 'has-warning' : 'is-ok'); node.querySelector('span:last-child').textContent = count ? count + ' 项提醒' : '系统运行正常'; }
function load() { app.innerHTML = '<div class="loading-state"><span></span><strong>正在读取本地情报库</strong></div>'; Promise.all([getJSON('/api/summary'),getJSON('/api/capabilities'),getJSON('/api/activity'),getJSON('/api/documents')]).then(function (values) { state.summary=values[0]; state.capabilities=values[1].items||[]; state.activity=values[2].items||[]; state.documents=values[3].items||[]; document.querySelector('#last-refresh').textContent='更新于 '+new Date().toLocaleTimeString('zh-CN',{hour12:false}); updateHealth(); render(); }).catch(function (error) { app.innerHTML='<div class="error-state"><strong>控制中心暂时无法读取数据</strong><p>'+esc(error.message)+'。请确认本地服务仍在运行。</p></div>'; }); }

document.addEventListener('click', function (event) {
  var viewTarget = event.target.closest('[data-view]'); if (viewTarget) { setView(viewTarget.dataset.view); return; }
  var capabilityTarget = event.target.closest('[data-capability-id]'); if (capabilityTarget) { var item = state.capabilities.find(function (candidate) { return candidate.repository === capabilityTarget.dataset.capabilityId; }); if (item) { renderCapabilityDetail(item); window.scrollTo(0,0); } return; }
  var repositoryTarget = event.target.closest('[data-repository]'); if (repositoryTarget) { var found = state.capabilities.find(function (candidate) { return candidate.repository === repositoryTarget.dataset.repository; }); if (found) renderCapabilityDetail(found); return; }
  var documentTarget = event.target.closest('[data-document]'); if (documentTarget) { openDocument(documentTarget.dataset.document); return; }
  var copy = event.target.closest('[data-copy]'); if (copy && navigator.clipboard) navigator.clipboard.writeText(copy.dataset.copy).then(function () { var old = copy.textContent; copy.textContent='已复制'; setTimeout(function () { copy.textContent=old; },1200); });
});
document.querySelector('[data-action=refresh]').addEventListener('click',load);
initTheme(); load();
